fixed eval bar on puzzle pages
prettierlichess/prettierlichess pull request #49
Opened 2021-05-20 07:47 UTC by TheTrio

Closes #48 

<img width="600" src="https://user-images.githubusercontent.com/10794178/118938558-6cecd900-b96c-11eb-8b57-5d0229f0031d.png" >

Do note that this fixes the evaluation bar for screen sizes bigger than 1260px(width). The reason for that is because the extension presently disables the evaluation bar for screen sizes smaller than 1260px, and I wasn't sure if I should change that. 

Do let me know what you guys think.

2021-05-20 13:31 UTC, Durush reviewed
Gonna defer to @noahsemus on this one not sure what his intentions were for this. Thoughts Noah?

2021-05-20 13:34 UTC, noahsemus requested changes
Testing this now, I am not getting a fix. Seems as though the puzzle__tools div is overlapping the board and then on finish moves back to it's intended position.

![image](https://user-images.githubusercontent.com/33107099/118987789-9434ad80-b94e-11eb-95cc-4b11ed79da01.png)
![image](https://user-images.githubusercontent.com/33107099/118987820-9d257f00-b94e-11eb-8f96-b5be0c4ef060.png)

2021-05-20 14:05 UTC, TheTrio commented
I'm unable to reproduce this bug. Lemme see if I can find the problem.

2021-06-10 21:12 UTC, closed without merging

2021-06-10 21:12 UTC, TheTrio commented
Closing this for now. Can't seem to find the problem.